# Generated by Django 3.2.18 on 2023-05-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite_recipes',
            name='unique_favorite',
        ),
        migrations.AddConstraint(
            model_name='favorite_recipes',
            constraint=models.UniqueConstraint(fields=('user_id', 'recipes_id'), name='grocery_assistant_favorite_recipes_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoping_list',
            constraint=models.UniqueConstraint(fields=('user_id', 'recipes_id'), name='unique_cart'),
        ),
    ]
