# Generated by Django 3.2 on 2023-04-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_assistant', '0002_favorite_recipes_follow_ingredients_ingredients_list_shoping_list_tags_tags_list_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_recipes',
            name='recipes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_assistant.recipes', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favorite_recipes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользовтель'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='Slag тег'),
        ),
        migrations.AlterField(
            model_name='tags_list',
            name='recipes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_assistant.recipes', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='tags_list',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_assistant.tags', verbose_name='Тег'),
        ),
    ]
