# Generated by Django 3.2.18 on 2023-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='grocery_assistant.IngredientRecipe', to='grocery_assistant.Ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='grocery_assistant.Tag', verbose_name='Таг'),
        ),
    ]
