# Generated by Django 3.2.18 on 2023-05-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_assistant', '0002_auto_20230510_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoping_list',
            name='recipes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping_list', to='grocery_assistant.recipes'),
        ),
        migrations.AlterField(
            model_name='shoping_list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
