# Generated by Django 3.2.18 on 2023-05-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0003_auto_20230511_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('000000', 'Черный'), ('ffa500', 'Оранжевый')], db_index=True, default='000000', max_length=16, unique=True, verbose_name='Цвет тега'),
        ),
    ]
