# Generated by Django 3.2.18 on 2023-05-18 17:19

from django.db import migrations, models
import grocery_assistant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0003_auto_20230518_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=16, validators=[grocery_assistant.validators.HexColorValidator()], verbose_name='Цвет тега в HEX формате'),
        ),
    ]
