# Generated by Django 3.2.18 on 2023-05-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
