# Generated by Django 3.2.18 on 2023-04-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0004_auto_20230423_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients_list',
            name='unit_id',
        ),
        migrations.DeleteModel(
            name='Unit_of_measure',
        ),
    ]
