# Generated by Django 3.2.18 on 2023-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0005_auto_20230425_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='ingredients_list',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Колличество ингридиента'),
        ),
    ]
