# Generated by Django 3.2.18 on 2023-04-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0006_auto_20230425_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredients_lists',
            field=models.ManyToManyField(through='grocery_assistant.Ingredients_list', to='grocery_assistant.Ingredients'),
        ),
    ]
