# Generated by Django 3.2.18 on 2023-04-28 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0008_recipes_tags_lists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite_recipes',
            options={'verbose_name_plural': 'Любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name_plural': 'Подписки на автора'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredients_list',
            options={'verbose_name_plural': 'Список ингридиентов'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoping_list',
            options={'verbose_name_plural': 'Список покупок'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tags_list',
            options={'verbose_name_plural': 'Список тегов'},
        ),
        migrations.AlterField(
            model_name='ingredients_list',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение >= 1')], verbose_name='Колличество ингридиента'),
            preserve_default=False,
        ),
    ]
