# Generated by Django 3.2.18 on 2023-04-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0009_auto_20230428_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Slag тег'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Тег'),
        ),
    ]
