# Generated by Django 3.2.18 on 2023-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0010_alter_tags_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('000000', '000000'), ('ffa500', 'ffa500')], db_index=True, default=('ffa500', 'ffa500'), max_length=16, unique=True, verbose_name='Цвет тега'),
        ),
    ]
