# Generated by Django 3.2.18 on 2023-04-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0010_auto_20230429_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-public_date', 'recipe_name'], 'verbose_name_plural': ('Рецепты',)},
        ),
    ]
