# Generated by Django 3.2.18 on 2023-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0011_alter_recipes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-public_date', 'recipe_name'], 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags_lists',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='grocery_assistant.Tags'),
        ),
        migrations.DeleteModel(
            name='Tags_list',
        ),
    ]
