# Generated by Django 3.2.18 on 2023-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0012_alter_tags_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('Черный', '#000000'), ('Оранжевый', '#ffa500')], db_index=True, default=('Оранжевый', '#ffa500'), max_length=16, unique=True, verbose_name='Цвет тега'),
        ),
    ]
