# Generated by Django 3.2.18 on 2023-04-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0012_auto_20230430_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients_list',
            name='ingr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_lists', to='grocery_assistant.ingredients', verbose_name='Ингридиент'),
        ),
    ]
