# Generated by Django 3.2.18 on 2023-04-30 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_assistant', '0018_alter_shoping_list_recipes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_recipes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Пользовтель'),
        ),
    ]
