# Generated by Django 3.2.18 on 2023-04-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_assistant', '0019_alter_favorite_recipes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_recipes',
            name='recipes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_favorite', to='grocery_assistant.recipes', verbose_name='Рецепт'),
        ),
    ]
